language: node_js
sudo: required
dist: trusty
node_js:
  - node
before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-setuptools python3-pip
  - sudo pip3 install --upgrade pip
  - pip3 install --user netaddr
